# SPDX-FileCopyrightText: 2020 Diego Elio Pettenò
#
# SPDX-License-Identifier: Unlicense

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: forbid-submodules

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v15.0.7
  hooks:
  - id: clang-format
    exclude: ^(src/ik_firmware.h|src/ik_loader.h)
    types_or: [c++, c, header]

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
  hooks:
  - id: codespell
    #args: [-w]
